### ISSUE TITLE
Regex used in decode is not quiet safe.

### ISSUE THREAD

**Issue by SkeLLLa** [mcollina/hyperid#12]
Steps to reproduce:
1. Use regex from https://github.com/mcollina/hyperid/blob/master/hyperid.js#L71
2. Try execute
```
"foo/bar/1/5e21e41c47d675ba57f51f5b".match(/(.*)+\/(\d+)+$/)
```
3. Observe that browser/node hangs trying to match this regex.

**Comment by SkeLLLa** [comment]
@mcollina I don't know exactly, but I'd rather avoid regex match if it possible.

**Comment by mcollina** [comment]
PR?

**Comment by SkeLLLa** [comment]
@mcollina can you describe the id format that this lib produces? I'm not sure that I'm right.
Or it's as I guessed: `<base64 encoded uuid>/<counter>`?

**Comment by mcollina** [comment]
that's the idea, yes.

**Comment by SkeLLLa** [comment]
Then, I'll make PR soon.
Just was confused about 
```
(.*)+\/(\d+)+$
           ^^ - this "+"
```

**Comment by mcollina** [comment]
the last + is redundant.
