### ISSUE TITLE
Jest has detected the following 1 open handle potentially keeping Jest from exiting

### ISSUE THREAD

**Issue by tylerlong** [mcollina/hyperid#22]
Code is simple:

```ts
import hyperid from 'hyperid';
const uuid = hyperid();
```

Version 2.1.0

<img width="644" alt="Screen Shot 2021-01-11 at 10 26 35 AM" src="https://user-images.githubusercontent.com/733544/104222717-877bd800-53f7-11eb-9fab-7f169b6c252e.png">

**Comment by mcollina** [comment]
I'm truly certain this is not the case. Please consider opening this issue against jest. There is nothing I can do to fix a bug that is not there in the first place.
