### ISSUE TITLE
bump uuid version

### ISSUE THREAD

**Issue by panmau** [mcollina/hyperid#23]
[Slonik](https://github.com/gajus/slonik/) uses your package and I got the following warning when installing it:
`hyperid > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`
Can & should we bump the version of the uuid package used here?

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by panmau** [comment]
Sure. I will give it a try.
