### ISSUE TITLE
The v2.3.0 version dose not work

### ISSUE THREAD

**Issue by taoyuan** [mcollina/hyperid#26]
The v2.3.0 version does not work due to the missing uuid.js file.

It will throw the error below when running:
```
Error: Cannot find module './uuid'
Require Stack:
-  ....
-  ...
-  ...
```

**Comment by hardik-ebiz** [comment]
+1 yes this is critical issue and happening on a production app made with  loopback-next and has dependency on hyperid

**Comment by lonewolfaka9** [comment]
@taoyuan  temporary workaround is to use previous version which does not depends on latest version of UUID

> npm i hyperid@2.1.0

**Comment by mcollina** [comment]
v2.3.1 is out fixing this.

**Comment by mcollina** [comment]
I'm sorry about the hiccup!

**Comment by hardik-ebiz** [comment]
thanks mate

**Comment by taoyuan** [comment]
👍
