### ISSUE TITLE
urlSafe swaps +- and /_ encoding as per RFC 4648

### ISSUE THREAD

**Issue by michaelrommel** [mcollina/hyperid#28]
Hi Matteo,

in line 70 https://github.com/mcollina/hyperid/blob/364c2520866ed697854298237bbb87f374963dfb/hyperid.js#L70 the urlSafe option triggers a replacement of `+` with `_` and of `/` with `-`.

Per RFC4648 (https://datatracker.ietf.org/doc/html/rfc4648#page-8) it should be exactly opposite. Since nobody knows, how the users of hyperid use the resulting id and if they are depending on exactly this conversion, it might be a breaking change if you wanted the RFC behaviour.

Since I do not know, if the swap was intentional or not, I have not (yet) created a PR. It is not an issue for me, as I am about to swap out hyperid with a combination of standard `crypto.randomUUID` plus a nanoid, just because for starters I do not need the extreme raw performance and security folks do not want an enumerable ID...

But I - of course - will create a PR, if you'd like. After all, it is just a two-line change (`decode` function is affected, too). I could not find test cases which would need adaptation. 

Cheers,

  Michael.

**Comment by mcollina** [comment]
Sure thing, send a PR over!
